import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.review.deleteMany();
  await prisma.sellerProduct.deleteMany();
  await prisma.seller.deleteMany();

  await prisma.sellerProduct.createMany({
    data: [
      {
        title: "AirPods Pro 2 — Premium Wireless",
        description: "Беспроводные наушники с активным шумоподавлением. Адаптивный EQ, прозрачный режим, 30ч работы с кейсом. Совместимы с iOS и Android.",
        price: 249900,
        oldPrice: 349900,
        costPrice: 150000,
        stock: 25,
        imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600",
        category: "Электроника",
        sellerName: "TechZone UA",
        rating: 4.8,
        reviewCount: 124,
        views: 1820,
        isTrending: true,
        isRecommended: true,
      },
      {
        title: "Xiaomi Mi Power Bank 3 Pro 20000mAh",
        description: "Портативный аккумулятор 20000mAh с быстрой зарядкой 45W. 3 USB-A + 1 USB-C. Заряжает ноутбук, планшет и телефон одновременно.",
        price: 89900,
        oldPrice: 119900,
        costPrice: 50000,
        stock: 48,
        imageUrl: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600",
        category: "Гаджеты",
        sellerName: "Xiaomi Official UA",
        rating: 4.7,
        reviewCount: 89,
        views: 990,
        isTrending: true,
        isRecommended: false,
      },
      {
        title: "Механическая клавиатура KEYCHRON K2 RGB",
        description: "Компактная 75% механическая клавиатура с RGB-подсветкой, Gateron Brown switches. Bluetooth + USB-C, алюминиевый корпус.",
        price: 189900,
        oldPrice: 229900,
        costPrice: 110000,
        stock: 15,
        imageUrl: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=600",
        category: "Gaming",
        sellerName: "GameZone",
        rating: 4.9,
        reviewCount: 67,
        views: 760,
        isTrending: false,
        isRecommended: true,
      },
      {
        title: "Xiaomi Mi Watch S1 Active — Смарт-часы",
        description: "Смарт-часы с AMOLED-дисплеем, GPS, мониторингом ЧСС и SpO2. 12 дней работы от батареи. 117+ режимов тренировок.",
        price: 149900,
        oldPrice: 199900,
        costPrice: 90000,
        stock: 30,
        imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
        category: "Гаджеты",
        sellerName: "Xiaomi Official UA",
        rating: 4.6,
        reviewCount: 53,
        views: 640,
        isTrending: false,
        isRecommended: true,
      },
      {
        title: "Видеорегистратор 70mai Dash Cam Pro Plus+",
        description: "Автомобильный видеорегистратор 2.7K, Sony IMX335, GPS, ADAS, 140° широкий угол. Ночная съёмка без шумов.",
        price: 119900,
        oldPrice: null,
        costPrice: 70000,
        stock: 20,
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        category: "Авто",
        sellerName: "AutoParts UA",
        rating: 4.5,
        reviewCount: 41,
        views: 510,
        isTrending: true,
        isRecommended: false,
      },
      {
        title: "Робот-пылесос Roborock S7 MaxV",
        description: "Умный робот-пылесос с лазерной навигацией, мощностью всасывания 5100 Pa, вибрационной шваброй. Совместим с Alexa и Google Home.",
        price: 899900,
        oldPrice: 1099900,
        costPrice: 550000,
        stock: 8,
        imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600",
        category: "Дом",
        sellerName: "SmartHome UA",
        rating: 4.9,
        reviewCount: 38,
        views: 820,
        isTrending: false,
        isRecommended: true,
      },
      {
        title: "Кроссовки Nike Air Max 270 — Реплика",
        description: "Лёгкие беговые кроссовки с воздушной подушкой MAX Air. Сетчатый верх, резиновая подошва. Размеры 36–47. Доставка из Китая.",
        price: 129900,
        oldPrice: 179900,
        costPrice: 60000,
        stock: 60,
        imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
        category: "Одежда",
        sellerName: "FashionDrop UA",
        rating: 4.2,
        reviewCount: 95,
        views: 1340,
        isTrending: true,
        isRecommended: false,
      },
      {
        title: "Безопровидная зарядка Belkin 3-in-1",
        description: "Беспроводная зарядная станция для iPhone + Apple Watch + AirPods. MagSafe совместима. 15W быстрая зарядка.",
        price: 99900,
        oldPrice: 129900,
        costPrice: 55000,
        stock: 35,
        imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600",
        category: "Электроника",
        sellerName: "TechZone UA",
        rating: 4.4,
        reviewCount: 28,
        views: 430,
        isTrending: false,
        isRecommended: false,
      },
      {
        title: "Bluetooth-колонка JBL Charge 5",
        description: "Портативная водонепроницаемая колонка с мощностью 40W. IP67, 20ч автономной работы, PowerBank функция. Стерео-звук с Bass Radiator.",
        price: 279900,
        oldPrice: 359900,
        costPrice: 170000,
        stock: 18,
        imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600",
        category: "Электроника",
        sellerName: "AudioPro UA",
        rating: 4.7,
        reviewCount: 112,
        views: 1250,
        isTrending: true,
        isRecommended: true,
      },
      {
        title: "LED лента RGB 10м с Bluetooth управлением",
        description: "Светодиодная лента 10м с приложением управления, 16 млн цветов. Для комнаты, ТВ-подсветки, геймерского стола. Самоклеящаяся основа.",
        price: 49900,
        oldPrice: 74900,
        costPrice: 25000,
        stock: 100,
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        category: "Дом",
        sellerName: "SmartHome UA",
        rating: 4.3,
        reviewCount: 76,
        views: 870,
        isTrending: false,
        isRecommended: false,
      },
    ],
  });

  await prisma.seller.createMany({
    data: [
      {
        name: "Олексій Петров",
        shopName: "TechZone UA",
        email: "techzone@chinamarket.ua",
        phone: "+380671234567",
        category: "Электроника",
        description: "Официальный реселлер электроники из Китая. Работаем с 2019 года.",
        status: "APPROVED",
        rating: 4.8,
        verified: true,
      },
      {
        name: "Марина Коваль",
        shopName: "FashionDrop UA",
        email: "fashion@chinamarket.ua",
        phone: "+380679876543",
        category: "Одежда",
        description: "Модная одежда и обувь из Китая по доступным ценам.",
        status: "APPROVED",
        rating: 4.2,
        verified: false,
      },
    ],
  });

  console.log("✅ Database seeded with 10 products and 2 sellers");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
